---
title: "Homework 6"
author: "Jiarui Fu"
date: "11/20/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(broom)
library(modelr)
library(mgcv)
```

## Problem 1
```{r}
birthweight = read.csv("data/birthweight.csv") 
birthweight_clean = birthweight %>%  
  select(-parity, -pnumlbw, -pnumsga) %>%
  mutate(babysex = factor(babysex),
         frace = factor(frace),
         malform = factor(malform),
         mrace = factor(mrace)) %>% 
  mutate(babysex = fct_infreq(babysex),
         frace = fct_infreq(frace),
         malform = fct_infreq(malform),
         mrace = fct_infreq(mrace)) %>% 
  mutate(babysex = recode(babysex, "1" = "male", "2" = "female"),
         frace = recode(frace, "1" = "White", "2" = "Black", "3" = "Asian", "4" = "Puerto Rican", "8" = "Other", "9" = "Unknown"),
         malform = recode(malform, "0" = "absent", "1" = "present"),
         mrace = recode(mrace, "1" = "White", "2" = "Black", "3" = "Asian", "4" = "Puerto Rican", "8" = "Other"))

fit0 = lm(bwt ~ ., data = birthweight_clean)
summary(fit0)

birthweight_fit = birthweight_clean %>% 
  select(babysex, bhead, blength, bwt, gaweeks, mrace, smoken, wtgain) 

fit = lm(bwt ~ babysex + gaweeks + bhead * mrace + blength * smoken + wtgain, data = birthweight_fit)
summary(fit)

birthweight_clean %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x = pred, y = resid)) + geom_point() 

model1 = lm(bwt ~ blength + gaweeks, data = birthweight_fit)
summary(model1)
model2 = lm(bwt ~ bhead * blength * babysex, data = birthweight_fit)
summary(model2)

cv_df = crossv_mc(birthweight_fit, 100)
cv_df = 
  cv_df %>% 
  mutate(fit = map(train, ~lm(bwt ~ babysex + gaweeks + bhead * mrace + blength * smoken + wtgain, data = birthweight_fit)),
         model1 = map(train, ~lm(bwt ~ blength + gaweeks, data = birthweight_fit)),
         model2 = map(train, ~lm(bwt ~ bhead * blength * babysex, data = birthweight_fit))) %>% 
  mutate(rmse_fit = map2_dbl(fit, test, ~rmse(model = .x, data = .y)),
         rmse_model1 = map2_dbl(model1, test, ~rmse(model = .x, data = .y)),
         rmse_model2 = map2_dbl(model2, test, ~rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

## Problem 2
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

bootstrap_regression = 
weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x) ),
    tidied = map(models, broom::tidy),
    glanced = map(models, glance)) %>% 
  select(-strap, -models) 

bootstrap_beta = 
  bootstrap_regression %>% 
  select(-glanced) %>% 
  unnest(tidied) 


bootstrap_rsq = 
  bootstrap_regression %>% 
  select(-tidied) %>% 
  unnest(glanced)

```
